name: Setup PNPM
description: Set up Node and PNPM
inputs:
  pnpm_version:
    description: PNPM version to use
    default: latest
  node_version:
    description: NodeJS version to use
    default: "20"
  bun_version:
    description: Bun version to use
    default: latest

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun_version }}
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm_version }}
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_ENV
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm install
